-- INDOORS_INDEX = {
--     [0] = archery_minigame_inside,
--     [1] = hc_main_entrance_inside,
--     [2] = hc_left_entrance_inside,
--     [3] = hc_right_entrance_inside,
--     [4] = sanctuary_entrance_inside,
--     [5] = ce_dropdown_entrance_inside,
--     [6] = at_entrance_inside,
--     [7] = ep_entrance_inside,
--     [8] = dp_main_entrance_inside,
--     [9] = dp_left_entrance_inside,
--     [10] = dp_right_entrance_inside,
--     [11] = dp_back_entrance_inside,
--     [12] = toh_entrance_inside,
--     [13] = pod_entrance_inside,
--     [14] = sp_entrance_inside,
--     [15] = sw_big_chest_entrance_inside,
--     [16] = sw_gibdo_entrance_inside,
--     [17] = sw_west_lobby_entrance_inside,
--     [18] = sw_bottom_left_drop_inside,
--     [19] = sw_north_drop_inside,
--     [20] = sw_pinball_drop_inside,
--     [21] = sw_pot_circle_drop_inside,
--     [22] = sw_back_entrance_inside,
--     [23] = tt_entrance_inside,
--     [24] = ip_entrance_inside,
--     [25] = mm_entrance_inside,
--     [26] = tr_main_entrance_inside,
--     [27] = tr_laser_entrance_inside,
--     [28] = tr_big_chest_entrance_inside,
--     [29] = tr_eye_bridge_entrance_inside,
--     [30] = gt_entrance_inside,
--     [31] = aginah_cave_inside,
--     [32] = archery_minigame_inside,
--     [33] = cave45_inside,
--     [34] = checkerboard_cave_inside,
--     [35] = dam_desert_fairy_inside,
--     [36] = dam_inside,
--     [37] = dam_top_right_cave_inside,
--     [38] = darf_smiths_inside,
--     [39] = eastern_fairy_inside,
--     [40] = graveyard_fairy_inside,
--     [41] = graveyard_ledge_inside,
--     [42] = icerod_cave_inside,
--     [43] = icerod_cave_inside,
--     [44] = icerod_fairy_inside,
--     [45] = icerod_stone_inside,
--     [46] = kakariko_blinds_hideout_inside,
--     [47] = kakariko_bombhut_inside,
--     [48] = kakariko_chickenhut_inside,
--     [49] = kakariko_frontside_pub_inside,
--     [50] = kakariko_house_hill_top_inside,
--     [51] = kakariko_house_right_center_inside,
--     [52] = kakariko_house_right_top_inside,
--     [53] = kakariko_house_top_left_inside,
--     [54] = kakariko_shop_inside,
--     [55] = kakariko_sick_kid_inside,
--     [56] = kakariko_well_cave_inside,
--     [57] = kakariko_well_hole_inside,
--     [58] = kings_tomb_inside,
--     [59] = kings_tomb_inside,
--     [60] = library_inside,
--     [61] = inverted_bumper_cave_inside,
--     [62] = light_bumper_cave_inside,
--     [63] = light_death_mountain_ascent_inside,
--     [64] = light_death_mountain_cave1_inside,
--     [65] = light_death_mountain_cave2_inside,
--     [66] = light_death_mountain_cave3_inside,
--     [67] = _insidelight_death_mountain_old_man_cave_outside_inside,
--     [68] = light_death_mountain_shop_inside,
--     [69] = light_eyebridge_fairy_inside,
--     [70] = light_lake_fortune_inside,
--     [71] = light_lake_shop_inside,
--     [72] = light_potion_shop_inside,
--     [73] = links_fairy_fountain_inside,
--     [74] = links_house_inside,
--     [75] = lost_woods_fortune_inside,
--     [76] = lost_woods_hideout_cave_inside,
--     [77] = lost_woods_hideout_hole_inside,
--     [78] = lost_woods_top_inside,
--     [79] = lumberjacks_cave_inside,
--     [80] = lumberjacks_hole_inside,
--     [81] = lumberjacks_house_inside,
--     [82] = magic_bat_cave_inside,
--     [83] = magic_bat_hole_inside,
--     [84] = mimic_cave_inside,
--     [85] = mini_moldorm_cave_inside,
--     [86] = old_man_cave_inside,
--     [87] = old_man_cave_inside,
--     [88] = paradox_cave_bottom_entrance_inside,
--     [89] = paradox_cave_top_entrance_inside,
--     [90] = sahasralahs_hut_inside,
--     [91] = sanctuary_entrance_inside,
--     [92] = sanctuary_bonk_pile_cave_inside,
--     [93] = secret_passage_hole_inside,
--     [94] = secret_passage_stairs_inside,
--     [95] = shooting_gallery_inside,
--     [96] = spec_rock_ledge_entrance_inside,
--     [97] = spec_rock_ledge_exit_inside,
--     [98] = spec_rock_top_entrance_inside,
--     [99] = spiral_cave_bottom_inside,
--     [100] = spiral_cave_top_inside,
--     [101] = twenty_rupee_thief_inside,
--     [102] = twin_house_left_inside,
--     [103] = twin_house_right_inside,
--     [104] = upgrade_fairy_inside,
--     [105] = waterfall_fairy_inside,
--     [106] = witchhut_inside,
--     [107] = big_bomb_shop_inside,
--     [108] = big_bomb_shop_fairy_cave_inside,
--     [109] = brewery_inside,
--     [110] = dark_bumper_cave_inside,
--     [111] = c_shaped_house_inside,
--     [112] = chest_game_inside,
--     [113] = dark_aghina_inside,
--     [114] = dark_archery_minigame_inside,
--     [115] = dark_chapel_inside,
--     [116] = dark_desert_hint_cave_inside,
--     [117] = dark_death_mountain_shop_inside,
--     [118] = dark_icerod_cave_inside,
--     [119] = dark_icerod_fairy_inside,
--     [120] = dark_icerod_stone_inside,
--     [121] = dark_lake_shop_inside,
--     [122] = dark_lumpberjacks_shop_inside,
--     [123] = dark_old_man_cave_inside,
--     [124] = dark_potion_shop_inside,
--     [125] = dark_village_shop_inside,
--     [126] = hookshot_cave_inside,
--     [127] = hype_cave_inside,
--     [128] = hype_cave_back_inside,
--     [129] = kiki_cave_inside,
--     [130] = mire_shed_left_inside,
--     [131] = mire_shed_right_inside,
--     [132] = peg_cave_inside,
--     [133] = pod_fairy_cave_inside,
--     [134] = pod_teleport_cave_inside,
--     [135] = pyramid_fairy_cave_inside,
--     [136] = pyramid_inside,
--     [137] = red_shield_shop_inside,
--     [138] = spike_cave_inside,
--     [139] = superbunny_cave_inside,
--     [140] = superbunny_cave_bottom_inside,
--     [141] = superbunny_cave_top_inside,
--     [142] = at_entrance_inside,
--     [143] = ce_dropdown_entrance_inside,
--     [144] = ce_stairs_inside,
--     [145] = dp_back_entrance_inside,
--     [146] = dp_left_entrance_inside,
--     [147] = dp_main_entrance_inside,
--     [148] = dp_right_entrance_inside,
--     [149] = ep_entrance_inside,
--     [150] = gt_entrance_inside,
--     [151] = hc_left_entrance_inside,
--     [152] = hc_main_entrance_inside,
--     [153] = hc_right_entrance_inside,
--     [154] = ip_entrance_inside,
--     [155] = mm_entrance_inside,
--     [156] = pod_entrance_inside,
--     [157] = sp_entrance_inside,
--     [158] = sw_back_entrance_inside,
--     [159] = sw_big_chest_entrance_inside,
--     [160] = sw_bottom_left_drop_inside,
--     [161] = sw_gibdo_entrance_inside,
--     [162] = sw_north_drop_inside,
--     [163] = sw_pinball_drop_inside,
--     [164] = sw_pot_circle_drop_inside,
--     [165] = sw_west_lobby_entrance_inside,
--     [166] = toh_entrance_inside,
--     [167] = tr_big_chest_entrance_inside,
--     [168] = tr_eye_bridge_entrance_inside,
--     [169] = tr_laser_entrance_inside,
--     [170] = tr_main_entrance_inside,
--     [171] = tt_entrance_inside
-- }
INDOORS_INDEX = {

}

OUTDOORS_INDEX = {
    
}


function CreateDoorsLuaitems()
    for _, location in pairs(NAMED_LOCATIONS) do
        -- print(location.name)
        if string.sub(location.name, -7,-1) == "_inside" then
            CreateLuaLocationItems(location.name, location.shortname, "inside")
            
        elseif string.sub(location.name, -8,-1) == "_outside" then
            CreateLuaLocationItems(location.name, location.shortname, "outside")
        end
        if string.sub(location.name, -7,-1) == "_inside"  or string.sub(location.name, -8,-1) == "_outside" then
            -- print(Tracker:FindObjectForCode(location.name).Active)
            -- local test = Tracker:FindObjectForCode(location.name)
            -- test.Active = true--Set("Active", false)
            -- print(Tracker:FindObjectForCode(location.name).Active)
        end
        -- print(Tracker:FindObjectForCode(location.name).Active)
    end
    return 1
end
Tracker.BulkUpdate = true
CreateDoorsLuaitems()
Tracker.BulkUpdate = false