-- use this file to map the AP item ids to your items
-- first value is the code of the target item and the second is the item type (currently only "toggle", "progressive", ""and "toggle", ""but feel free to expand for your needs!)
-- here are the SM items as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/item_mapping.lua
ITEM_mapPING = {
[11]   =   {"bow+arrow", "toggle"}
[100]   =   {"bow", "progressive"}
[101]   =   {"bow", "progressive"}
[88]   =   {"Silver Arrows", ""}
[59]   =   {"bow+silvers", "toggle"}
[29]   =   {"book", "toggle"}
[9]   =    {"hammer", "toggle"}
[10]   =   {"hookshot", "toggle"}
[26]   =   {"mirror", "toggle"}
[20]   =   {"flute", "toggle"}
[75]   =   {"boots", "toggle"}
[27]   =   {"powergloves", "toggle"}
[25]   =   {"cape", "toggle"}
[41]   =   {"mushroom", "progressive"}
[19]   =   {"shovel", "progressive"}
[18]   =   {"lamp", "toggle"}
[13]   =   {"powder", "progressive"}
[31]   =   {"Mpearl", "toggle"}
[21]   =   {"somaria", "toggle"}
[7]   =    {"firerod", "toggle"}
[30]   =   {"flippers", "toggle"}
[8]   =    {"icerod", "toggle"}
[28]   =   {"titans", "toggle"}
[15]   =   {"bombos", "toggle"}
[16]   =   {"ether", "toggle"}
[17]   =   {"quake", "toggle"}
[22]   =   {"bottle", "progressive"}
[43]   =   {"bottle", "progressive"}
[44]   =   {"bottle", "progressive"}
[45]   =   {"bottle", "progressive"}
[61]   =   {"bottle", "progressive"}
[60]   =   {"bottle", "progressive"}
[72]   =   {"bottle", "progressive"}
[80]   =   {"mastersword", "toggle"}
[2]   =    {"temperedsword", "toggle"}
[73]   =   {"fightersword", "toggle"}
[3]   =    {"goldensword", "toggle"}
[94]   =   {"sword", "progressive"}
[97]   =   {"glove", "progressive"}
[106]   =   {"Triforce", ""}
[107]   =   {"Power Star", ""}
[108]   =   {"triforcepiece", "progressive"}
[67]   =   {"Single Arrow", ""}
[68]   =   {"Arrows (10)", ""}
[84]   =   {"Arrow Upgrade (+10)", "progressive"}
[83]   =   {"Arrow Upgrade (+5)", "progressive"}
[39]   =   {"Single Bomb", ""}
[40]   =   {"Bombs (3)", ""}
[49]   =   {"Bombs (10)", ""}
[82]   =   {"bombs", "progressive"}
[81]   =   {"bombs", "progressive"}
[34]   =   {"blue_mail", "toggle"}
[35]   =   {"red_mail", "toggle"}
[96]   =   {"armor", "progressive"}
[12]   =   {"blueboomerang", "toggle"}
[42]   =   {"redboomerang", "toggle"}
[4]   =    {"blueshield", "toggle"}
[5]   =    {"redshield", "toggle"}
[6]   =    {"mirrorshield", "toggle"}
[95]   =   {"shield", "progressive"}
[33]   =   {"bugcatchingnet", "toggle"}
[24]   =   {"byrna", "toggle"}
[62]   =   {"heartcontainer", "progressive"}
[63]   =   {"heartcontainer", "progressive"}
[23]   =   {"heartpiece", "progressive"}
[52]   =   {"Rupee (1)", ""}
[53]   =   {"Rupees (5)", ""}
[54]   =   {"Rupees (20)", ""}
[65]   =   {"Rupees (50)", ""}
[64]   =   {"Rupees (100)", ""}
[70]   =   {"Rupees (300)", ""}
[89]   =   {"Rupoor", ""}
[91]   =   {"Red Clock", ""}
[92]   =   {"Blue Clock", ""}
[93]   =   {"Green Clock", ""}
[98]   =   {"Single RNG", ""}
[99]   =   {"Multi RNG", ""}
[78]   =   {"half_magic", "progressive"}
[79]   =   {"quarter_magic", "progressive"}
[162]   =   {"ep_smallkey", "progressive"}
[157]   =   {"ep_bigkey", "toggle"}
[141]   =   {"ep_compass", "toggle"}
[125]   =   {"ep_map", "toggle"}
[163]   =   {"dp_smallkey", "progressive"}
[156]   =   {"dp_bigkey", "toggle"}
[140]   =   {"dp_compass", "toggle"}
[124]   =   {"dp_map", "toggle"}
[170]   =   {"toh_smallkey", "progressive"}
[149]   =   {"toh_bigkey", "toggle"}
[133]   =   {"toh_compass", "toggle"}
[117]   =   {"toh_map", "toggle"}
[160]   =   {"hc_smallkey", "progressive"}
[159]   =   {"hc_bigkey", "toggle"}
[143]   =   {"hc_compass", "toggle"}
[127]   =   {"hc_map", "toggle"}
[164]   =   {"at_smallkey", "progressive"}
[155]   =   {"at_bigkey", "toggle"}
[139]   =   {"at_compass", "toggle"}
[123]   =   {"at_map", "toggle"}
[166]   =   {"pod_smallkey", "progressive"}
[153]   =   {"pod_bigkey", "toggle"}
[137]   =   {"pod_compass", "toggle"}
[121]   =   {"pod_map", "toggle"}
[171]   =   {"tt_smallkey", "progressive"}
[148]   =   {"tt_bigkey", "toggle"}
[132]   =   {"tt_compass", "toggle"}
[116]   =   {"tt_map", "toggle"}
[168]   =   {"sw_smallkey", "progressive"}
[151]   =   {"sw_bigkey", "toggle"}
[135]   =   {"sw_compass", "toggle"}
[119]   =   {"sw_map", "toggle"}
[165]   =   {"sp_smallkey", "progressive"}
[154]   =   {"sp_bigkey", "toggle"}
[138]   =   {"sp_compass", "toggle"}
[122]   =   {"sp_map", "toggle"}
[169]   =   {"ip_smallkey", "progressive"}
[150]   =   {"ip_bigkey", "toggle"}
[134]   =   {"ip_compass", "toggle"}
[118]   =   {"ip_map", "toggle"}
[167]   =   {"mm_smallkey", "progressive"}
[152]   =   {"mm_bigkey", "toggle"}
[136]   =   {"mm_compass", "toggle"}
[120]   =   {"mm_map", "toggle"}
[172]   =   {"tr_smallkey", "progressive"}
[147]   =   {"tr_bigkey", "toggle"}
[131]   =   {"tr_compass", "toggle"}
[115]   =   {"tr_map", "toggle"}
[173]   =   {"gt_smallkey", "progressive"}
[146]   =   {"gt_bigkey", "toggle"}
[130]   =   {"gt_compass", "toggle"}
[114]   =   {"gt_map", "toggle"}
[175]   =   {"smallkey (Universal)", "progressive"}
[90]   =   {"Nothing", ""}
[176]   =   {"Bee Trap", ""}
[177]   =   {"Faerie", ""}
[178]   =   {"Good Bee", ""}
[179]   =   {"Magic Jar", ""}
[180]   =   {"Apple", ""}
[46]   =   {"Red Potion", ""}
[47]   =   {"Green Potion", ""}
[48]   =   {"Blue Potion", ""}
[14]   =   {"Bee", ""}
[66]   =   {"Small Heart", ""}
[74]   =   {"Activated Flute", "toggle"}


    [3860226] = {"stonebadge", "toggle"},
    [3860227] = {"knucklebadge", "toggle"},
    [3860228] = {"dynamobadge", "toggle"},
    [3860229] = {"heatbadge", "toggle"},
    [3860230] = {"balancebadge", "toggle"},
    [3860231] = {"featherbadge", "toggle"},
    [3860232] = {"mindbadge", "toggle"},
    [3860233] = {"rainbadge", "toggle"},
    [3860339] = {"hm01", "toggle"},
    [3860340] = {"hm02", "toggle"},
    [3860341] = {"hm03", "toggle"},
    [3860342] = {"hm04", "toggle"},
    [3860343] = {"hm05", "toggle"},
    [3860344] = {"hm06", "toggle"},
    [3860345] = {"hm07", "toggle"},
    [3860346] = {"hm08", "toggle"},
    [3860259] = {"machbike", "toggle"},
    [3860272] = {"acrobike", "toggle"},
    [3860269] = {"devongoods", "toggle"},
    [3860274] = {"letter", "toggle"},
    [3860261] = {"itemfinder", "toggle"},
    [3860280] = {"meteorite", "toggle"},
    [3860279] = {"gogoggles", "toggle"},
    [3860281] = {"roomkey1", "toggle"},
    [3860282] = {"roomkey2", "toggle"},
    [3860283] = {"roomkey4", "toggle"},
    [3860284] = {"roomkey6", "toggle"},
    [3860285] = {"storagekey", "toggle"},
    [3860278] = {"scanner", "toggle"},
    [3860271] = {"basementkey", "toggle"},
    [3860288] = {"devonscope", "toggle"},
    [3860375] = {"magmaemblem", "toggle"},
    [3860273] = {"pokeblock", "toggle"},
    [3860265] = {"ssticket", "toggle"},
    [3860268] = {"wailmerpail", "toggle"},
    [3860262] = {"oldrod", "toggle"},
    [3860263] = {"goodrod", "toggle"},
    [3860264] = {"superrod", "toggle"},
    [3860122] = {"harbormail", "toggle"}
}