--teleporter

Teleporter_at_kakariko_village = alttp_location.new("Teleporter_at_kakariko_village", "Kakariko Teleporter (OW)", "light", "Lightworld OW", false)
Teleporter_at_village_of_the_outcast = alttp_location.new("Teleporter_at_village_of_the_outcast", "Dark Village Teleporter (OW)", "dark", "Darkworld OW", false)
Teleporter_at_light_turtle_rock = alttp_location.new("Teleporter_at_light_turtle_rock", "Light DM TR Teleporter (OW)", "light", "Lightworld OW", false)
Teleporter_at_dark_turtle_rock = alttp_location.new("Teleporter_at_dark_turtle_rock", "TR Back Teleporter (OW)", "dark", "Darkworld OW", false)
Teleporter_at_light_death_mountain_right_bottom = alttp_location.new("Teleporter_at_light_death_mountain_right_bottom", "Light DM Right Teleporter (OW)", "light", "Lightworld OW", false)
Teleporter_at_light_death_mountain_left_bottom = alttp_location.new("Teleporter_at_light_death_mountain_left_bottom", "Light DM Left Teleporter (OW)", "light", "Lightworld OW", false)
Teleporter_at_dark_death_mountain_left_bottom = alttp_location.new("Teleporter_at_dark_death_mountain_left_bottom", "Dark DM Left Teleporter (OW)", "dark", "Darkworld OW", false)
Teleporter_at_dark_death_mountain_right_bottom = alttp_location.new("Teleporter_at_dark_death_mountain_right_bottom", "Dark DM Right Teleporter (OW)", "dark", "Darkworld OW", false)
Teleporter_at_eastern = alttp_location.new("Teleporter_at_eastern", "EP Teleporter (OW)", "light", "Lightworld OW", false)
Teleporter_at_pod = alttp_location.new("Teleporter_at_pod", "PoD Teleporter (OW)", "dark", "Darkworld OW", false)
Teleporter_at_desert = alttp_location.new("Teleporter_at_desert", "Desert Teleporter (OW)", "light", "Lightworld OW", false)
Teleporter_at_mire = alttp_location.new("Teleporter_at_mire", "Mire Teleporter (OW)", "dark", "Darkworld OW", false)
Teleporter_at_dam = alttp_location.new("Teleporter_at_dam", "Dam Teleporter (OW)", "light", "Lightworld OW", false)
Teleporter_at_swamp = alttp_location.new("Teleporter_at_swamp", "Swamp Teleporter (OW)", "dark", "Darkworld OW", false)
Teleporter_at_upgrade_fairy = alttp_location.new("Teleporter_at_upgrade_fairy", "Upgrade Fairy Teleporter (OW)", "light", "Lightworld OW", false)
Teleporter_at_ice_palace = alttp_location.new("Teleporter_at_ice_palace", "IP Teleporter (OW)", "dark", "Darkworld OW", false)


Old_man_cave_left_outside = alttp_location.new("Old_man_cave_left_outside", "Old Man Cave Left (OW)", "light", "Lightworld OW", false, 10, 1448, nil, 696, 711, {"Lost Woods - Entrances", "Old Man Cave Exit (West)", "Old Man Cave Exit (West)"})
Old_man_cave_left_inside = alttp_location.new("Old_man_cave_left_inside", "Old Man Cave Left (Inside)", nil, "Lightworld caves", false, 240, 120, nil, 8152, 8180, {"Lost Woods - Insides", "Old Man Cave Exit (West)", "Old Man Cave Exit (West)"}, "connector")
Old_man_cave_right_outside = alttp_location.new("Old_man_cave_right_outside", "Old Man Cave Right (OW)", "light", "Lightworld OW", false, 3, 1656, nil, 744, 757, {"Light Death Mountain - Entrances", "Old Man Cave (East)","Old Man Cave (East)"})
Old_man_cave_right_inside = alttp_location.new("Old_man_cave_right_inside", "Old Man Cave Right (Inside)", nil, "Lightworld caves", false, 241, 888, nil, 8128, 8181, {"Light Death Mountain - Insides", "Old Man Cave (East)","Old Man Cave (East)"}, "connector")

Light_death_mountain_return_left_outside = alttp_location.new("Light_death_mountain_return_left_outside", "DM Return Left (OW)", "light", "Lightworld OW", false, 10, 1464, nil, 599, 615, {"Lost Woods - Entrances", "Death Mountain Return Cave Exit (West)", "Death Mountain Return Cave Exit (West)"})
Light_death_mountain_return_left_inside = alttp_location.new("Light_death_mountain_return_left_inside", "DM Return Left (Inside)", nil, "Lightworld caves", false, 230, 3192, nil, 7616, 7668, {"Lost Woods - Insides", "Death Mountain Return Cave Exit (West)", "Death Mountain Return Cave Exit (West)"}, "connector")
Light_death_mountain_return_right_outside = alttp_location.new("Light_death_mountain_return_right_outside", "DM Return Right (OW)", "light", "Lightworld OW", false, 3, 1608, nil, 536, 550, {"Light Death Mountain - Entrances", "Death Mountain Return Cave (East)", "Death Mountain Return Cave (East)"})
Light_death_mountain_return_right_inside = alttp_location.new("Light_death_mountain_return_right_inside", "DM Return Right (Inside)", nil, "Lightworld caves", false, 231, 3960, nil, 7616, 7668, {"Light Death Mountain - Insides", "Death Mountain Return Cave (East)", "Death Mountain Return Cave (East)"}, "connector")

Bumpercave_bottom_outside = alttp_location.new("Bumpercave_bottom_outside", "Bumpercave Bottom (OW)", "dark", "Darkworld OW", false, nil, nil, nil, nil, nil, {"Skull Woods - Entrances", "Bumper Cave (Bottom)", "Bumper Cave (Bottom)"})
Bumpercave_bottom_inside = alttp_location.new("Bumpercave_bottom_inside", "Bumpercave Bottom (Inside)", nil, "Darkworld caves", false, nil, nil, nil, nil, nil, {"Skull Woods - Insides", "Bumper Cave (Bottom)", "Bumper Cave (Bottom)"}, "connector")
Bumpercave_top_outside = alttp_location.new("Bumpercave_top_outside", "Bumpercave Top (OW)", "dark", "Darkworld OW", false, nil, nil, nil, nil, nil, {"Skull Woods - Entrances", "Bumper Cave (Top)", "Bumper Cave (Top)"})
Bumpercave_top_inside = alttp_location.new("Bumpercave_top_inside", "Bumpercave Top (Inside)", nil, "Darkworld caves", false, nil, nil, nil, nil, nil, {"Skull Woods - Insides", "Bumper Cave (Top)", "Bumper Cave (Top)"}, "connector")
Bumpercave_top_back = alttp_location.new("Bumpercave_top_back", "Bumpercave Top Back", "dark", "Darkworld caves", false)
Bumpercave_top_front = alttp_location.new("Bumpercave_top_front", "Bumpercave Top Front", "dark", "Darkworld caves", false)