Tracker:Addscript/logic("script/logic/darkworld.json")
Tracker:Addscript/logic("script/logic/lightworld.json")
Tracker:Addscript/logic("script/logic/HC.json")
Tracker:Addscript/logic("script/logic/AT.json")
Tracker:Addscript/logic("script/logic/EP.json")
Tracker:Addscript/logic("script/logic/DP.json")
Tracker:Addscript/logic("script/logic/ToH.json")
Tracker:Addscript/logic("script/logic/PoD.json")
Tracker:Addscript/logic("script/logic/SP.json")
Tracker:Addscript/logic("script/logic/SW.json")
Tracker:Addscript/logic("script/logic/TT.json")
Tracker:Addscript/logic("script/logic/MM.json")
Tracker:Addscript/logic("script/logic/IP.json")
Tracker:Addscript/logic("script/logic/TR.json")
Tracker:Addscript/logic("script/logic/GT.json")
-- Tracker:Addscript/logic("script/logic/bosses.json")
-- Tracker:Addscript/logic("script/logic/retrocaves.json")