Tracker:Addscript("script/logic/location_definition.lua")
Tracker:Addscript("script/logic/darkworld.lua")
Tracker:Addscript("script/logic/lightworld.lua")
Tracker:Addscript("script/logic/HC.lua")
Tracker:Addscript("script/logic/AT.lua")
Tracker:Addscript("script/logic/EP.lua")
Tracker:Addscript("script/logic/DP.lua")
Tracker:Addscript("script/logic/ToH.lua")
Tracker:Addscript("script/logic/PoD.lua")
Tracker:Addscript("script/logic/SP.lua")
Tracker:Addscript("script/logic/SW.lua")
Tracker:Addscript("script/logic/TT.lua")
Tracker:Addscript("script/logic/MM.lua")
Tracker:Addscript("script/logic/IP.lua")
Tracker:Addscript("script/logic/TR.lua")
Tracker:Addscript("script/logic/GT.lua")
-- Tracker:Addscript/logic("script/logic/bosses.json")
-- Tracker:Addscript/logic("script/logic/retrocaves.json")