require("scripts.logic.location_definition_light")
require("scripts.logic.location_definition_dark")
require("scripts.logic.location_definition_dungeons")
require("scripts.logic.location_definition_teleporters")
require("scripts/logic/darkworld")
require("scripts/logic/lightworld")
require("scripts/logic/HC")
require("scripts/logic/AT")
require("scripts/logic/EP")
require("scripts/logic/DP")
require("scripts/logic/ToH")
require("scripts/logic/PoD")
require("scripts/logic/SP")
require("scripts/logic/SW")
require("scripts/logic/TT")
require("scripts/logic/MM")
require("scripts/logic/IP")
require("scripts/logic/TR")
require("scripts/logic/GT")
-- Tracker:Addscript/logic("script/logic/bosses.json")
-- Tracker:Addscript/logic("script/logic/retrocaves.json")