ScriptHost:LoadScript("scripts/logic/location_definition.lua")
ScriptHost:LoadScript("scripts/logic/darkworld.lua")
ScriptHost:LoadScript("scripts/logic/lightworld.lua")
ScriptHost:LoadScript("scripts/logic/HC.lua")
ScriptHost:LoadScript("scripts/logic/AT.lua")
ScriptHost:LoadScript("scripts/logic/EP.lua")
ScriptHost:LoadScript("scripts/logic/DP.lua")
ScriptHost:LoadScript("scripts/logic/ToH.lua")
ScriptHost:LoadScript("scripts/logic/PoD.lua")
ScriptHost:LoadScript("scripts/logic/SP.lua")
ScriptHost:LoadScript("scripts/logic/SW.lua")
ScriptHost:LoadScript("scripts/logic/TT.lua")
ScriptHost:LoadScript("scripts/logic/MM.lua")
ScriptHost:LoadScript("scripts/logic/IP.lua")
ScriptHost:LoadScript("scripts/logic/TR.lua")
ScriptHost:LoadScript("scripts/logic/GT.lua")
-- Tracker:Addscript/logic("script/logic/bosses.json")
-- Tracker:Addscript/logic("script/logic/retrocaves.json")